-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgWwcCvqPS4ElJyAiFRoRF52ji6b/5MgnahC7ccd2WBtKgCgYIKoZIzj0DAQehRANCAAQbJnK/h0w+AFsvjOSnvBTJfoKKfBmOMXfriT4fu9cFTRlH2q5h7GFwpSBa8bbG7+IZJuO9Wx6g+ZZzKX/FwV1+
-----END PRIVATE KEY-----